### ISSUE TITLE
Automatic directory creation

### ISSUE THREAD

**Issue by jennmald** [NSLS-II-TES/profile_collection#18]
From the call for experiment prep with @mrakitin , the directories for `/nsls2/data/tes/legacy/detectors/cam6/hdf5/%Y/%m/%d/` are not created automatically.

**Comment by mrakitin** [comment]
The feature was originally added to `ophyd` via https://github.com/bluesky/ophyd/pull/996.

**Comment by mrakitin** [comment]
Closing as it's taken care of by Ansible.
